### ISSUE TITLE
'Debug Python File' does nothing

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-python-debugger#102]
1. Open Python file in a folder that doesn't have a launch config defined
2. Set breakpoint
3. From editor title run menu, choose 'Debug Python File'
4. :bug: nothing happens

![Image](https://github.com/microsoft/vscode-python-debugger/assets/30305945/097b8634-5eaf-4439-9222-9d6056027caa)

**Comment by joyceerhl** [comment]
Note that if I go into the Run/Debug view and choose the Python Debugger launch config, then F5 to debug, that works

**Comment by XuShenLZ** [comment]
I am having a similar issue here. I am developing in a docker container with Python 3.6.9. The Python Debugger Extension version is `v2023.1.12492010`

When I open the "Run and Debug" panel on the left side and hit the green button for "Debugpy: Python File" or "Debugpy: Current File", I can debug my python file and stop at the breakpoint. As below:

![image](https://github.com/microsoft/vscode-python-debugger/assets/31999415/ca375740-8544-4074-b1fc-2db87d796d34)

However, if I click the small "run and debug" button on the top right corner, it seems that it still uses the "Python Extension" (rather than Debugger Extension) so that I get the error of Python version less than 3.7 is not supported.

![image](https://github.com/microsoft/vscode-python-debugger/assets/31999415/4acad358-86b2-4941-84bc-1008392e91cc)

My host machine and VS Code version:

> Version: 1.83.0
> Commit: e7e037083ff4455cf320e344325dacb480062c3c
> Date: 2023-10-03T16:11:49.843Z
> Electron: 25.8.4
> ElectronBuildId: 24154031
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Linux x64 6.2.0-26-generic snap

Python version: 3.6.9
Dev Container version: v0.315.0
Python extension version: v2023.16.0
Python Debugger Extension version: v2023.1.12492010

**Comment by paulacamargo25** [comment]
Duplicated: https://github.com/microsoft/vscode-python-debugger/issues/137
