### ISSUE TITLE
Name debug console automatically using launch.json file

### ISSUE THREAD

**Issue by alon710** [microsoft/vscode-python-debugger#176]
Today users can change console names manually after executing their code

![image](https://github.com/microsoft/vscode-python/assets/35544532/c8c502e5-7a8a-4f5f-8d4a-e3f69bb1f9cc)

I want to be able to change the console name before I launch my application using the launch.json configuration file
for example:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Module Name",
            "type": "python",
            "request": "launch",
            "module": "path.to.module",
            "consoleName": "My Console Name" // or apply the name of the module automatically
        }
    ]
}
```
The team at Vascode has introduced support for this feature, but its implementation is also required in the Python extension.
https://github.com/microsoft/vscode/issues/128108#issuecomment-1373901239

**Comment by paulacamargo25** [comment]
Thanks for the feature request! We are going to give the community 60 days from when this issue was created to provide 7 👍 upvotes on the opening comment to gauge general interest in this idea. If there's enough upvotes then we will consider this feature request in our future planning. If there's unfortunately not enough upvotes then we will close this issue.
