### ISSUE TITLE
Unable to install previous versions on VSCode. 2024 is the only version available.

### ISSUE THREAD

**Issue by JanieHuang** [microsoft/vscode-python-debugger#193]
To replicate:
1. Go to VSCode Extensions
2. Click "Install other version" 
3. Only available one is the current 2024 release, no other way to go to previous versions

![image](https://github.com/microsoft/vscode-python-debugger/assets/7298898/d6a01389-b1bc-4568-9948-f602a10f4c65)

Currently on Ubuntu, but I was able to easily replicate this on Windows. 

I was able to pull up version lists for other extensions, but it seems this plugin (as well as in the Releases tab on GitHub) seemed to be wiped.

**Comment by paulacamargo25** [comment]
@JanieHuang  thanks for your issue report. 2024.0.0 is the only version that we have in release, that's why you can only see one. To install pre-release versions, first change the version to pre-release  by clicking on `Switch to Pre-Release Version`

<img width="704" alt="Screenshot 2024-02-05 at 4 32 23 PM" src="https://github.com/microsoft/vscode-python-debugger/assets/17892325/dd7c1f3c-570d-4bb2-ad18-32b76e03fae2">

And then click on "Install other version". There you can see all the pre-release versions that we have.

Thanks

**Comment by Cbnbrain** [comment]
Thanks

**Comment by Hylixen** [comment]
It's hard to get previous version releases of extension. When you are using old version of vscode, you can't install the latest debugger due to compatibility exp (Unable to install extension 'ms-python.python' as it is not compatible with VS Code '1.75.1'.). Just install it manually, you'll find that no old versions extension in the [market](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy) and in the offical git repository releases just source code. When you want to debug python <= 3.6, then  just spend days to find the compatible extension from the internet.   :( 
May there add previuos version in the market? thx

**Comment by realyyz** [comment]
> It's hard to get previous version releases of extension. When you are using old version of vscode, you can't install the latest debugger due to compatibility exp (Unable to install extension 'ms-python.python' as it is not compatible with VS Code '1.75.1'.). Just install it manually, you'll find that no old versions extension in the [market](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy) and in the offical git repository releases just source code. When you want to debug python <= 3.6, then just spend days to find the compatible extension from the internet. :( May there add previuos version in the market? thx

There is an version of debugger called "debugpy old" in the extensions of vscode. You can try that one.

**Comment by Sam-1968R** [comment]
![٢٠٢٥٠١٢٤_١٥٤٤١٣.jpg](https://github.com/user-attachments/assets/2fd0f856-313d-429e-9b20-b1a52033fbc3)

**Comment by Jerad551** [comment]
Troubleshooting-TensorBoard-integration-in-VS-Code.md[Troubleshooting-TensorBoard-integration-in-VS-Code.md](url)https://devblogs.microsoft.com/python/python-in-visual-studio-code-february-2021-release/vscode-language-pascalhttps://github.com/alefragnani/vscode-language-pascalext install rlugtigheid.sip-protocol-highlightext install eamodio.gitlens
