### ISSUE TITLE
The 'Python Debugger' extension is not available in VSCodium for Linux ARM 64

### ISSUE THREAD

**Issue by PureTryOut** [microsoft/vscode-python-debugger#318]
I'm running VSCodium on Linux on Apple Silicon, thus the aarch64 CPU architecture. It is complaining about `"type": "python"` in my `launch.json` and that I have to replace it with `debugpy` before it's being deprecated. That type seems to be provided by this extension but I can't actually install it due to the error in the title.

This extension is pure Typescript, is there any reason at all it wouldn't work on Linux ARM machines?

**Comment by paulacamargo25** [comment]
Thanks for your bug report, I am going to investigate what is happening.

**Comment by imphil** [comment]
Drive-by comment (I have a similar, but different problem): It looks like the Python Debugger extension is actually platform-specific since https://github.com/microsoft/vscode-python-debugger/pull/89 (it includes Python wheels?). 

That alone doesn't explain your problem, I guess, since aarch64 seems to be included in https://github.com/microsoft/vscode-python-debugger/blob/7b2177d3a0dc8211891d6d6dccfce02317476c73/build/azure-pipeline.stable.yml#L40-L42.

**Comment by filiptronicek** [comment]
Hey there 👋, 
I believe this to be a problem on our end, since I assume you're using https://open-vsx.org as the extension marketplace. We are in the process of adding the linux arm platform in https://github.com/open-vsx/publish-extensions/pull/756 for the extension, but I need to figure out how to tweak the build pipeline to install the correct platform-specific dependencies :).

Feel free to track that PR or https://github.com/open-vsx/publish-extensions/issues/755 for updates.

**Comment by PureTryOut** [comment]
Oh, I didn't realize it was basically a packaging problem. I'm using whatever comes with VSCodium, and I believe indeed that is https://open-vsx.org. Thanks for finding this issue, I'll close this and wait for the update to appear!

@imphil you're listing the arm64 package for macOS, but I'm actually running on Linux.
