### ISSUE TITLE
VSCode won't launch when using APIs (e.g. Fusion API)

### ISSUE THREAD

**Issue by cadop** [microsoft/vscode-python-debugger#340]
It seems at first glance this PR caused some external linking to vscode to break. 

https://github.com/microsoft/vscode-python/pull/23211

Could be that poor practice was used by other devs, but it would also be nice to have vs-code revert to the old system when it is broken. 

Related discussion:
https://forums.autodesk.com/t5/fusion-api-and-scripts/visual-studio-not-launching-when-selecting-edit-add-ins/td-p/10053282

**Comment by karthiknadig** [comment]
@cadop The issue is that Autodesk Fusion is not using or accessing the debugger in the prescribed way. They has hard coded the path to the debugger in the extension. Unfortunately, we can't predict or support such scenarios. We have a API surface for that reason to make it stable for dependents to access it. 

The best option is to pin the extension to the version where it worked. Better yet, `debugpy` is a library of its own, MIT licensed, and can be shipped with fusion. That way Fusion can control the end to end experience.
